FROM python:3.11-buster

ENV PYTHONUNBUFFERED=1

# Create working directory
WORKDIR /code

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Install dependencies
COPY pyproject.toml poetry.lock* README.md /code/
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Copy project code
COPY . /code/

# Expose Django port
EXPOSE 8000
STOPSIGNAL SIGINT
