# Generated by Django 5.2.4 on 2025-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('cuisine', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-rating'],
            },
        ),
    ]
