# Generated by Django 5.2.4 on 2025-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_userrestaurantinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
